title: Ayesha Riaz
logo: /assets/img/headshot_circle.png
description: Self-driven and motivated senior Software Engineer student adept at developing and implementing new software platforms, along with testing software products. Possessing great analytical skills, ability to work in team environment, and strong attention detail.
show_downloads: true
theme: jekyll-theme-minimal
