title: Ayesha Riaz Ahmed
logo: /images/Untitled.png {width: 400px ,hight:300px}
description: Self-driven and motivated senior Software Engineer student adept at developing and implementing new software platforms, along with creating software products. Possessing great analytical skills, ability to work in team environment, and strong attention detail.
show_downloads: false
theme: jekyll-theme-minimal
